### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by xunkai55** [badpoet/SQLeast#1]
@pzz2011

可以在issue里讨论bugs，comment太难找了。

**Comment by xunkai55** [comment]
你可以看到那个bug是在build test-frontend的时候发生的，错误是unreferenced symbol，说明是构建test-frontend时没有正确链接静态库或目标文件。看test/CMakeLists.txt，加上正确的静态库就可以了。

为了科学，我把很多链接工作放在生成静态库之后立即完成了，比如src/ql/CMakeLists.txt里的那样。

**Comment by pzz2011** [comment]
@xunkai55  嗯，抱歉了。 多谢了。
